language: python

addons:
  hosts:
    - scriptobservatory.org

env: PATH_TO_STORE_SCRIPTCONTENT=/tmp/

python:
  - "3.4"

install:
  - "pip install -r requirements.txt"

script: nosetests misc/tests/
