language: python

addons:
  hosts:
    - scriptobservatory.org

sudo: required

env: PATH_TO_STORE_SCRIPTCONTENT=/tmp/ BACKEND_PORT=443

python:
  - "3.4"

install:
  - "pip install -r requirements.txt"

script: nosetests misc/tests/
