language: python

addons:
  hosts:
    - scriptobservatory.org

env: PATH_TO_STORE_SCRIPTCONTENT=/tmp/ BACKEND_PORT=8080

python:
  - "3.4"

install:
  - "pip install -r requirements.txt"

script: 
  - nosetests misc/tests/
