language: python

addons:
  hosts:
    - scriptobservatory.org

env: PATH_TO_STORE_SCRIPTCONTENT=/tmp/ BACKEND_PORT=8080

python:
  - "3.4"

install:
  - "pip install -r requirements.txt"

script: 
  - echo "archiving extension.js before we patch it to point to the local backend"
  - mv chrome-extension/extension.js chrome-extension/extension.js-arch
  - ls chrome-extension/
  - echo "patching extension.js"
  - sed 's/https:\/\/scriptobservatory.org/http:\/\/127.0.0.1:8080/g' chrome-extension/extension.js-arch > chrome-extension/extension.js
  - ls chrome-extension/
  - nosetests tests/
  - echo "restoring extension.js"
  - mv chrome-extension/extension.js-arch chrome-extension/extension.js
  - ls chrome-extension/
