language: python

sudo: required

addons:
  hosts:
    - scriptobservatory.org

env: RESOURCE_CONTENT_FOLDER=/tmp/ BACKEND_PORT=8080 LOG_FILEPATH=/tmp/

python:
  - "3.4"

install:
  - "pip install -r requirements.txt"

services:
  - redis-server

script: 
  - echo "trying chrome install (https://github.com/travis-ci/travis-ci/issues/938)"
  - ./tests/travis-ci-hacks.sh
  - echo "downloading chromedriver (64-bit, linux)"
  - wget https://chromedriver.storage.googleapis.com/2.15/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - echo "appending current directory to PATH"
  - export PATH=$(pwd):$PATH
  - echo "renaming config.py.example to config.py"
  - mv backend/config.py.example backend/config.py
  - echo "archiving robo-browser.py & extension.js before we patch them to point to the local backend"
  - mv chrome-extension/js/extension.js chrome-extension/js/extension.js-arch
  - mv robo-browser/robo-browser.py robo-browser/robo-browser.py-arch
  - ls chrome-extension/js/
  - ls robo-browser/
  - echo "patching extension.js"
  - sed 's/https:\/\/scriptobservatory.org/http:\/\/127.0.0.1:8080/g' chrome-extension/js/extension.js-arch > chrome-extension/js/extension.js
  - ls chrome-extension/js/
  - echo "patching robo-browser.py"
  - sed 's/https:\/\/scriptobservatory.org/http:\/\/127.0.0.1:8080/g' robo-browser/robo-browser.py-arch > robo-browser/robo-browser.py
  - ls robo-browser/
  - nosetests tests/
  - echo "restoring extension.js"
  - mv chrome-extension/js/extension.js-arch chrome-extension/js/extension.js
  - ls chrome-extension/js/
  - echo "restoring robo-browser.py"
  - mv robo-browser/robo-browser.py-arch robo-browser/robo-browser.py
  - ls robo-browser/
